"""sync_mesocycle_schema_with_models

Revision ID: 0df4238442db
Revises: 1e59ee66cb2a
Create Date: 2026-02-13 06:53:17.814781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df4238442db'
down_revision = '1e59ee66cb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesocycle_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mesocycle_template_id'], ['mesocycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesocycle_instances_id'), 'mesocycle_instances', ['id'], unique=False)
    op.create_index(op.f('ix_mesocycle_instances_mesocycle_template_id'), 'mesocycle_instances', ['mesocycle_template_id'], unique=False)
    op.create_index(op.f('ix_mesocycle_instances_status'), 'mesocycle_instances', ['status'], unique=False)
    op.create_index(op.f('ix_mesocycle_instances_user_id'), 'mesocycle_instances', ['user_id'], unique=False)
    op.add_column('mesocycles', sa.Column('is_stock', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('mesocycles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_mesocycles_status', table_name='mesocycles')
    op.create_index(op.f('ix_mesocycles_is_stock'), 'mesocycles', ['is_stock'], unique=False)
    op.drop_column('mesocycles', 'end_date')
    op.drop_column('mesocycles', 'status')
    op.drop_column('mesocycles', 'start_date')
    op.add_column('workout_sessions', sa.Column('mesocycle_instance_id', sa.Integer(), nullable=False))
    op.drop_index('ix_workout_sessions_mesocycle_id', table_name='workout_sessions')
    op.create_index(op.f('ix_workout_sessions_mesocycle_instance_id'), 'workout_sessions', ['mesocycle_instance_id'], unique=False)
    op.drop_constraint('workout_sessions_mesocycle_id_fkey', 'workout_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'workout_sessions', 'mesocycle_instances', ['mesocycle_instance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_sessions', 'mesocycle_id')
    op.add_column('workout_sets', sa.Column('skipped', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'skipped')
    op.add_column('workout_sessions', sa.Column('mesocycle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.create_foreign_key('workout_sessions_mesocycle_id_fkey', 'workout_sessions', 'mesocycles', ['mesocycle_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workout_sessions_mesocycle_instance_id'), table_name='workout_sessions')
    op.create_index('ix_workout_sessions_mesocycle_id', 'workout_sessions', ['mesocycle_id'], unique=False)
    op.drop_column('workout_sessions', 'mesocycle_instance_id')
    op.add_column('mesocycles', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mesocycles', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('mesocycles', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mesocycles_is_stock'), table_name='mesocycles')
    op.create_index('ix_mesocycles_status', 'mesocycles', ['status'], unique=False)
    op.alter_column('mesocycles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mesocycles', 'is_stock')
    op.drop_index(op.f('ix_mesocycle_instances_user_id'), table_name='mesocycle_instances')
    op.drop_index(op.f('ix_mesocycle_instances_status'), table_name='mesocycle_instances')
    op.drop_index(op.f('ix_mesocycle_instances_mesocycle_template_id'), table_name='mesocycle_instances')
    op.drop_index(op.f('ix_mesocycle_instances_id'), table_name='mesocycle_instances')
    op.drop_table('mesocycle_instances')
    # ### end Alembic commands ###
