"""add workout_feedback table

Revision ID: 1c50099fca6d
Revises: 0df4238442db
Create Date: 2026-02-13 07:42:09.837059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c50099fca6d'
down_revision = '0df4238442db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_feedback_id'), 'workout_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_workout_feedback_workout_session_id'), 'workout_feedback', ['workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_feedback_workout_session_id'), table_name='workout_feedback')
    op.drop_index(op.f('ix_workout_feedback_id'), table_name='workout_feedback')
    op.drop_table('workout_feedback')
    # ### end Alembic commands ###
