"""add exercise_notes to mesocycle_instances

Revision ID: 78a113184164
Revises: a1b2c3d4e5f6
Create Date: 2026-02-16 13:57:14.964092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a113184164'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesocycle_instances', sa.Column('exercise_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesocycle_instances', 'exercise_notes')
    # ### end Alembic commands ###
